# Generated by Django 3.0.3 on 2020-05-25 08:15

import ckeditor_uploader.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PostCategories',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(blank=True, help_text='The name of the page as it will appear in URLs e.g http://domain.com/blog/category/[my-slug]/', max_length=150, null=True, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Categories',
                'ordering': ['category'],
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, unique=True)),
                ('content', ckeditor_uploader.fields.RichTextUploadingField()),
                ('shortContent', models.TextField(blank=True, max_length=400)),
                ('image', models.ImageField(blank=True, help_text='The picture for thumbnail', null=True, upload_to='blogApp/post/')),
                ('slug', models.SlugField(blank=True, help_text='The name of the page as it will appear in URLs e.g http://domain.com/blog/[my-slug]/', max_length=150, null=True, unique=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('status', models.BooleanField(choices=[(False, 'Draft'), (True, 'Publish')], default=False)),
                ('featured', models.BooleanField(choices=[(False, 'Regular'), (True, 'Featured')], default=False)),
                ('view', models.PositiveIntegerField(default=0)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blog_posts', to=settings.AUTH_USER_MODEL)),
                ('categories', models.ManyToManyField(null=True, related_name='categories', to='blogApp.PostCategories')),
            ],
            options={
                'ordering': ['-created_on'],
            },
        ),
    ]
