# Generated by Django 3.0.3 on 2020-05-29 15:29

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='content',
            field=ckeditor_uploader.fields.RichTextUploadingField(help_text='Full images can be 730px wide'),
        ),
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, help_text='Thumbnail Image  1600x1200', null=True, upload_to='blogApp/post/'),
        ),
        migrations.AlterField(
            model_name='post',
            name='shortContent',
            field=models.TextField(blank=True, help_text='Max Characters = 370', max_length=370),
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(max_length=110, unique=True),
        ),
    ]
