# Generated by Django 3.0.3 on 2020-06-13 10:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blogApp', '0002_auto_20200529_1529'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='language',
            field=models.CharField(choices=[('EN', 'English'), ('FA', 'Farsi')], default='EN', max_length=10),
        ),
        migrations.AddField(
            model_name='postcategories',
            name='category_lang',
            field=models.CharField(choices=[('EN', 'English'), ('FA', 'Farsi')], default='EN', max_length=10),
        ),
        migrations.AlterField(
            model_name='post',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='authors', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='post',
            name='slug',
            field=models.SlugField(allow_unicode=True, blank=True, help_text='The name of the page as it will appear in URLs e.g http://domain.com/blog/[my-slug]/', max_length=150, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='postcategories',
            name='slug',
            field=models.SlugField(allow_unicode=True, blank=True, help_text='The name of the page as it will appear in URLs e.g http://domain.com/blog/category/[my-slug]/', max_length=150, null=True, unique=True),
        ),
    ]
