# Generated by Django 3.0.3 on 2020-06-16 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogApp', '0003_auto_20200613_1029'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, help_text='Thumbnail Image  1200x630', null=True, upload_to='blogApp/post/'),
        ),
    ]
