# Generated by Django 3.0.3 on 2020-07-02 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogApp', '0004_auto_20200616_1752'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, help_text='Thumbnail Image  1068x710', null=True, upload_to='blogApp/post/'),
        ),
    ]
