# Generated by Django 3.0.3 on 2020-08-27 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogApp', '0005_auto_20200702_1946'),
    ]

    operations = [
        migrations.AddField(
            model_name='postcategories',
            name='image',
            field=models.ImageField(blank=True, help_text='Banner Image 1920x1280', null=True, upload_to='blogApp/categories/'),
        ),
    ]
