# Generated by Django 3.0.3 on 2020-09-29 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogApp', '0006_postcategories_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='postcategories',
            name='description',
            field=models.TextField(blank=True, help_text='Max Characters = 800', max_length=800),
        ),
    ]
