# Generated by Django 3.2.3 on 2025-05-21 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegramApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chat_id', models.CharField(max_length=100)),
                ('user_id', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=50)),
                ('context', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'unique_together': {('chat_id', 'user_id')},
            },
        ),
    ]
