# Generated by Django 3.2.3 on 2025-05-21 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegramApp', '0002_userstate'),
    ]

    operations = [
        migrations.AddField(
            model_name='birthdayreminder',
            name='persian_birth_date',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
