# Generated by Django 3.2.3 on 2025-05-21 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegramApp', '0003_birthdayreminder_persian_birth_date'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ChatMember',
        ),
        migrations.AlterField(
            model_name='birthdayreminder',
            name='user_id',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='userstate',
            name='user_id',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='birthdayreminder',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='userstate',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='birthdayreminder',
            name='chat_id',
        ),
        migrations.RemoveField(
            model_name='userstate',
            name='chat_id',
        ),
    ]
