# Generated by Django 3.2.3 on 2025-05-21 11:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('telegramApp', '0004_auto_20250521_1044'),
    ]

    operations = [
        migrations.CreateModel(
            name='GlobalBirthday',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('birth_date', models.DateField()),
                ('persian_birth_date', models.CharField(blank=True, max_length=20)),
                ('added_by', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'unique_together': {('name', 'birth_date')},
            },
        ),
        migrations.CreateModel(
            name='UserBirthdayExclusion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('birthday', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='telegramApp.globalbirthday')),
            ],
            options={
                'unique_together': {('user_id', 'birthday')},
            },
        ),
        migrations.CreateModel(
            name='UserBirthdaySettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=100)),
                ('user_name', models.CharField(max_length=100)),
                ('reminder_days', models.IntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('birthday', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='telegramApp.globalbirthday')),
            ],
            options={
                'unique_together': {('user_id', 'birthday')},
            },
        ),
        migrations.DeleteModel(
            name='BirthdayReminder',
        ),
    ]
