# Generated by Django 3.2.3 on 2025-05-22 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegramApp', '0005_auto_20250521_1105'),
    ]

    operations = [
        migrations.AddField(
            model_name='globalbirthday',
            name='telegram_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='globalbirthday',
            name='added_by',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='globalbirthday',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
