# Generated by Django 3.2.3 on 2025-05-22 06:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('telegramApp', '0006_auto_20250522_0237'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='globalbirthday',
            unique_together={('name', 'birth_date', 'added_by')},
        ),
        migrations.DeleteModel(
            name='UserBirthdayExclusion',
        ),
    ]
