# Generated by Django 3.2.3 on 2025-05-22 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegramApp', '0007_auto_20250522_0640'),
    ]

    operations = [
        migrations.AddField(
            model_name='globalbirthday',
            name='reminder_days',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
