# Generated by Django 3.2.3 on 2025-05-24 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegramApp', '0009_telegramadmin'),
    ]

    operations = [
        migrations.AddField(
            model_name='globalbirthday',
            name='last_reminder_sent',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='globalbirthday',
            name='snoozed_until',
            field=models.DateField(blank=True, null=True),
        ),
    ]
