# Generated by Django 3.0.3 on 2020-05-25 08:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('FL', 'Flat'), ('VI', 'Villa'), ('OF', 'Office'), ('ST', 'Store')], default='FL', max_length=150)),
                ('price', models.DecimalField(decimal_places=0, default=0.0, max_digits=15)),
                ('bathroom', models.PositiveIntegerField(default=1)),
                ('floors', models.PositiveIntegerField()),
                ('build_area', models.PositiveIntegerField(default=0)),
                ('featured', models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=False)),
                ('active', models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=True)),
                ('tag', models.CharField(choices=[('FS', 'For Sale'), ('FR', 'For Rent')], default='FS', max_length=50)),
                ('image', models.ImageField(null=True, upload_to='baseApp/property/')),
                ('title', models.CharField(default='Comfortable Apartment', max_length=150)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='AssetFeatures',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('features', models.CharField(max_length=150, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Asset Features',
            },
        ),
        migrations.CreateModel(
            name='Bedroom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField(unique=True)),
                ('description', models.CharField(max_length=150, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
            ],
            options={
                'verbose_name_plural': 'Cities',
            },
        ),
        migrations.CreateModel(
            name='ComplexFeatures',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('features', models.CharField(max_length=150, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Complex Features',
            },
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('TR', 'Turkey'), ('IR', 'Iran'), ('AU', 'Australia')], default='TR', max_length=150)),
            ],
            options={
                'verbose_name_plural': 'Countries',
            },
        ),
        migrations.CreateModel(
            name='Slide',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='baseApp/slider/')),
                ('title', models.CharField(default='Find Your Home', max_length=150)),
                ('active', models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cities', to='baseApp.City')),
            ],
        ),
        migrations.CreateModel(
            name='Complex',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
                ('build_area', models.PositiveIntegerField(default=0)),
                ('description', models.TextField(blank=True, null=True)),
                ('features', models.ManyToManyField(to='baseApp.ComplexFeatures')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='regions', to='baseApp.Region')),
            ],
            options={
                'verbose_name_plural': 'Complexes',
            },
        ),
        migrations.AddField(
            model_name='city',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='countries', to='baseApp.Country'),
        ),
        migrations.CreateModel(
            name='AssetImages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(null=True, upload_to='baseApp/property/')),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='baseApp.Asset')),
            ],
            options={
                'verbose_name_plural': 'Asset Images',
            },
        ),
        migrations.AddField(
            model_name='asset',
            name='bedroom',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bedrooms', to='baseApp.Bedroom'),
        ),
        migrations.AddField(
            model_name='asset',
            name='complex',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='complexes', to='baseApp.Complex'),
        ),
        migrations.AddField(
            model_name='asset',
            name='features',
            field=models.ManyToManyField(to='baseApp.AssetFeatures'),
        ),
        migrations.AlterOrderWithRespectTo(
            name='asset',
            order_with_respect_to='created',
        ),
    ]
