# Generated by Django 3.0.3 on 2020-05-29 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baseApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='asset',
            options={'ordering': ['-created']},
        ),
        migrations.AddField(
            model_name='slide',
            name='useFor',
            field=models.CharField(choices=[('HOME', 'Homepage'), ('PROPERTY_SEARCH', 'Property Search'), ('PROPERTY_PAGE', 'Property View'), ('BLOG_HOME', 'Blog Homepage'), ('BLOG_SEARCH', 'Blog Search'), ('BLOG_CATEGORY', 'Blog Categories'), ('BLOG_POST', 'Blog Post')], default='HOME', max_length=50),
        ),
        migrations.AlterField(
            model_name='asset',
            name='image',
            field=models.ImageField(help_text='Thumbnail Image 1600x1200', null=True, upload_to='baseApp/property/'),
        ),
        migrations.AlterField(
            model_name='assetimages',
            name='image',
            field=models.ImageField(help_text='Slide Image 1600x1200', null=True, upload_to='baseApp/property/'),
        ),
        migrations.AlterField(
            model_name='slide',
            name='image',
            field=models.ImageField(blank=True, help_text='Slider Image 1920x1280', null=True, upload_to='baseApp/slider/'),
        ),
        migrations.AlterField(
            model_name='slide',
            name='title',
            field=models.CharField(default='Find Your Home', max_length=110),
        ),
        migrations.AlterOrderWithRespectTo(
            name='asset',
            order_with_respect_to=None,
        ),
    ]
