# Generated by Django 3.0.3 on 2020-05-30 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baseApp', '0002_auto_20200529_1529'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='features',
            field=models.ManyToManyField(blank=True, null=True, to='baseApp.AssetFeatures'),
        ),
        migrations.AlterField(
            model_name='complex',
            name='features',
            field=models.ManyToManyField(blank=True, null=True, to='baseApp.ComplexFeatures'),
        ),
    ]
