# Generated by Django 3.0.3 on 2020-05-30 21:12

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baseApp', '0003_auto_20200530_0911'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='assetimages',
            options={'ordering': ['display_order'], 'verbose_name_plural': 'Asset Images'},
        ),
        migrations.AddField(
            model_name='asset',
            name='description',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, help_text='Full images can be 730px wide', null=True),
        ),
        migrations.AddField(
            model_name='asset',
            name='garage',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='assetimages',
            name='display_order',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='assetimages',
            name='image',
            field=models.ImageField(help_text='Slide Image 1600x1100', null=True, upload_to='baseApp/property/'),
        ),
        migrations.AlterUniqueTogether(
            name='assetimages',
            unique_together={('asset', 'display_order')},
        ),
    ]
