# Generated by Django 3.0.3 on 2020-06-07 20:02

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baseApp', '0005_auto_20200531_2241'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='complexfeatures',
            options={'ordering': ['category', 'features'], 'verbose_name_plural': 'Complex Features'},
        ),
        migrations.AddField(
            model_name='complexfeatures',
            name='category',
            field=models.CharField(choices=[('GENERAL', 'General'), ('TECHNICAL', 'Technical'), ('SPORT', 'Sport'), ('TOP', 'Top'), ('LOCATION', 'Location')], default='GENERAL', max_length=150),
        ),
        migrations.AlterField(
            model_name='complex',
            name='description',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='region',
            name='description',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
    ]
