# Generated by Django 3.0.3 on 2020-06-09 17:53

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baseApp', '0006_auto_20200607_2002'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='description_FA',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, help_text='Full images can be 730px wide', null=True),
        ),
        migrations.AddField(
            model_name='asset',
            name='title_FA',
            field=models.CharField(blank=True, default='آپارتمانی راحت', max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='assetfeatures',
            name='features_FA',
            field=models.CharField(blank=True, max_length=150, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='bedroom',
            name='description_FA',
            field=models.CharField(blank=True, max_length=150, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='city',
            name='name_FA',
            field=models.CharField(blank=True, max_length=150, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='complex',
            name='description_FA',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='complexfeatures',
            name='features_FA',
            field=models.CharField(blank=True, max_length=150, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='region',
            name='description_FA',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='slide',
            name='title_FA',
            field=models.CharField(blank=True, default='خانه خود را پیدا کن', max_length=110, null=True),
        ),
        migrations.AlterField(
            model_name='city',
            name='name',
            field=models.CharField(max_length=150, unique=True),
        ),
    ]
