# Generated by Django 3.0.3 on 2020-06-21 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baseApp', '0007_auto_20200609_1753'),
    ]

    operations = [
        migrations.RenameField(
            model_name='asset',
            old_name='floors',
            new_name='floor',
        ),
        migrations.AddField(
            model_name='asset',
            name='build_area_gross',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='asset',
            name='dues',
            field=models.DecimalField(decimal_places=0, default=0.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='asset',
            name='heating_type',
            field=models.CharField(choices=[('CE', 'Central'), ('CO', 'Combi')], default='CE', max_length=10),
        ),
        migrations.AddField(
            model_name='asset',
            name='rental_income',
            field=models.DecimalField(decimal_places=0, default=0.0, max_digits=8),
        ),
        migrations.AlterField(
            model_name='asset',
            name='type',
            field=models.CharField(choices=[('FL', 'Flat'), ('VI', 'Villa'), ('OF', 'Office'), ('ST', 'Store')], default='FL', max_length=15),
        ),
        migrations.AlterField(
            model_name='complex',
            name='completion_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
