# Generated by Django 3.0.3 on 2020-06-28 20:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('baseApp', '0008_auto_20200621_1527'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
                ('name_FA', models.CharField(blank=True, max_length=150, null=True, unique=True)),
                ('icon_code', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='complexfeatures',
            name='category',
            field=models.CharField(choices=[('TOP', 'Top'), ('GENERAL', 'General'), ('TECHNICAL', 'Technical'), ('SPORT', 'Sport')], default='GENERAL', max_length=150),
        ),
        migrations.CreateModel(
            name='Distance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('distance', models.DecimalField(decimal_places=1, default=1.0, max_digits=6)),
                ('measure', models.CharField(choices=[('K', 'KM'), ('S', 'STEP'), ('M', 'MIN')], default='K', max_length=10)),
                ('measure_FA', models.CharField(blank=True, max_length=10, null=True)),
                ('complex', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='distances', to='baseApp.Complex')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='baseApp.Location')),
            ],
            options={
                'verbose_name_plural': 'Distances',
            },
        ),
        migrations.AddField(
            model_name='complex',
            name='near_locations',
            field=models.ManyToManyField(blank=True, null=True, through='baseApp.Distance', to='baseApp.Location'),
        ),
    ]
