# Generated by Django 3.0.3 on 2020-07-01 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baseApp', '0009_auto_20200628_2026'),
    ]

    operations = [
        migrations.AddField(
            model_name='complex',
            name='location_id',
            field=models.CharField(default='ChIJawhoAASnyhQR0LABvJj-zOE', help_text='https://developers.google.com/places/place-id', max_length=150),
        ),
        migrations.AlterField(
            model_name='distance',
            name='distance',
            field=models.DecimalField(decimal_places=0, default=1.0, max_digits=6),
        ),
    ]
