# Generated by Django 3.0.3 on 2020-07-03 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baseApp', '0010_auto_20200701_1057'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='complex',
            options={'ordering': ['name'], 'verbose_name_plural': 'Complexes'},
        ),
        migrations.AlterField(
            model_name='asset',
            name='rental_income',
            field=models.PositiveIntegerField(default=0, help_text='(For Sale): Rental Income or (For Rent): Deposit'),
        ),
    ]
