# Generated by Django 3.0.3 on 2020-07-19 19:10

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baseApp', '0011_auto_20200703_1914'),
    ]

    operations = [
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(choices=[('EN', 'English'), ('FA', 'Farsi')], default='EN', max_length=20)),
                ('question', models.CharField(max_length=300, unique=True)),
                ('answer', ckeditor_uploader.fields.RichTextUploadingField(blank=True, help_text='Full images can be 730px wide', null=True)),
                ('active', models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=True)),
                ('created', models.DateField(editable=False)),
                ('updated', models.DateField(editable=False)),
            ],
            options={
                'verbose_name_plural': 'FAQs',
                'ordering': ['created'],
            },
        ),
        migrations.RemoveField(
            model_name='asset',
            name='modified',
        ),
        migrations.AddField(
            model_name='asset',
            name='updated',
            field=models.DateField(editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='asset',
            name='created',
            field=models.DateField(editable=False),
        ),
        migrations.AlterField(
            model_name='slide',
            name='useFor',
            field=models.CharField(choices=[('HOME', 'Homepage'), ('PROPERTY_SEARCH', 'Property Search'), ('PROPERTY_PAGE', 'Property View'), ('BLOG_HOME', 'Blog Homepage'), ('BLOG_SEARCH', 'Blog Search'), ('BLOG_CATEGORY', 'Blog Categories'), ('BLOG_POST', 'Blog Post'), ('FAQ_PAGE', 'FAQ Page')], default='HOME', max_length=50),
        ),
    ]
