# Generated by Django 3.0.3 on 2020-07-31 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baseApp', '0012_auto_20200719_1910'),
    ]

    operations = [
        migrations.CreateModel(
            name='FAQCategories',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=100, unique=True)),
                ('category_lang', models.CharField(choices=[('EN', 'English'), ('FA', 'Farsi')], default='EN', max_length=10)),
                ('icon_code', models.CharField(blank=True, max_length=100, null=True)),
                ('slug', models.SlugField(allow_unicode=True, blank=True, help_text='The name of the page as it will appear in URLs e.g http://domain.com/FAQ/[category-slug]/', max_length=150, null=True, unique=True)),
            ],
            options={
                'verbose_name_plural': 'FAQ Categories',
                'ordering': ['category'],
            },
        ),
        migrations.AlterField(
            model_name='slide',
            name='useFor',
            field=models.CharField(choices=[('HOME', 'Homepage'), ('PROPERTY_SEARCH', 'Property Search'), ('PROPERTY_PAGE', 'Property View'), ('BLOG_HOME', 'Blog Homepage'), ('BLOG_SEARCH', 'Blog Search'), ('BLOG_CATEGORY', 'Blog Categories'), ('BLOG_POST', 'Blog Post'), ('FAQ_PAGE', 'FAQ Page'), ('FAQ_SEARCH', 'FAQ Search')], default='HOME', max_length=50),
        ),
        migrations.AddField(
            model_name='faq',
            name='categories',
            field=models.ManyToManyField(null=True, related_name='categories', to='baseApp.FAQCategories'),
        ),
    ]
