# Generated by Django 3.0.3 on 2020-09-02 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baseApp', '0013_auto_20200731_0917'),
    ]

    operations = [
        migrations.AddField(
            model_name='complex',
            name='hide_name',
            field=models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=False),
        ),
    ]
