# Generated by Django 3.0.3 on 2020-09-09 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baseApp', '0014_complex_hide_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='type',
            field=models.CharField(choices=[('FL', 'Flat'), ('DF', 'Dublex Flat'), ('VI', 'Villa'), ('OF', 'Office'), ('ST', 'Store')], default='FL', max_length=15),
        ),
    ]
