# Generated by Django 3.0.3 on 2020-09-09 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baseApp', '0015_auto_20200909_1611'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='base_price',
            field=models.DecimalField(decimal_places=0, default=0.0, max_digits=15),
        ),
    ]
