# Generated by Django 3.0.3 on 2020-09-13 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baseApp', '0016_asset_base_price'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='faq',
            options={'ordering': ['updated'], 'verbose_name_plural': 'FAQs'},
        ),
        migrations.AlterField(
            model_name='distance',
            name='measure',
            field=models.CharField(choices=[('K', 'KM'), ('ME', 'METER'), ('S', 'STEP'), ('M', 'MIN')], default='K', max_length=10),
        ),
    ]
