# Generated by Django 3.0.3 on 2020-09-13 18:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('baseApp', '0017_auto_20200913_0829'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='faq',
            name='categories',
        ),
    ]
