# Generated by Django 3.0.3 on 2020-09-13 18:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('baseApp', '0018_remove_faq_categories'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='faq',
            options={'verbose_name_plural': 'FAQs'},
        ),
        migrations.CreateModel(
            name='FAQPriority',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('priority', models.PositiveSmallIntegerField(default=100)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='baseApp.FAQCategories')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='priorities', to='baseApp.FAQ')),
            ],
            options={
                'verbose_name_plural': 'FAQ Priorities',
                'db_table': 'baseApp_faq_categories',
                'ordering': ['priority'],
            },
        ),
        migrations.AddField(
            model_name='faq',
            name='categories',
            field=models.ManyToManyField(null=True, related_name='categories', through='baseApp.FAQPriority', to='baseApp.FAQCategories'),
        ),
    ]
