# Generated by Django 3.0.3 on 2020-09-17 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baseApp', '0019_auto_20200913_1835'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slide',
            name='useFor',
            field=models.CharField(choices=[('HOME', 'Homepage'), ('PROPERTY_SEARCH', 'Property Search'), ('BLOG_HOME', 'Blog Homepage'), ('BLOG_SEARCH', 'Blog Search'), ('BLOG_CATEGORY', 'Blog Categories'), ('BLOG_POST', 'Blog Post'), ('FAQ_PAGE', 'FAQ Page'), ('FAQ_SEARCH', 'FAQ Search')], default='HOME', max_length=50),
        ),
    ]
