# Generated by Django 3.0.3 on 2021-05-07 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baseApp', '0020_auto_20200917_1315'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slide',
            name='useFor',
            field=models.CharField(choices=[('HOME', 'Homepage'), ('PROPERTY_SEARCH', 'Property Search'), ('BLOG_HOME', 'Blog Homepage'), ('BLOG_SEARCH', 'Blog Search'), ('BLOG_CATEGORY', 'Blog Categories'), ('BLOG_POST', 'Blog Post'), ('STORE_HOME', 'Store Home'), ('FAQ_PAGE', 'FAQ Page'), ('FAQ_SEARCH', 'FAQ Search')], default='HOME', max_length=50),
        ),
    ]
