# Generated by Django 3.2.2 on 2021-07-10 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baseApp', '0022_auto_20210514_1859'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slide',
            name='useFor',
            field=models.CharField(choices=[('HOME', 'Homepage'), ('ABOUT_US', 'About Us'), ('PROPERTY_SEARCH', 'Property Search'), ('BLOG_HOME', 'Blog Homepage'), ('BLOG_SEARCH', 'Blog Search'), ('BLOG_CATEGORY', 'Blog Categories'), ('BLOG_POST', 'Blog Post'), ('STORE_HOME', 'Store Home'), ('FAQ_PAGE', 'FAQ Page'), ('FAQ_SEARCH', 'FAQ Search')], default='HOME', max_length=50),
        ),
    ]
